### ISSUE TITLE
Amazing

### ISSUE THREAD

**Issue by timea-techgirl** [VChet/telegram-export-dark#1]
Hey! This is great and absolutely more than enough. My eyes are saved.

Just one issue I noticed. When I hover my mouse over sent/received files/gifs/stickers or "Next messages" or "Previous Messages" for longer chat exports, I see this white overlay.

![image](https://user-images.githubusercontent.com/7058205/188328417-33272874-9540-45d5-b3bf-9e864a891934.png)
![image](https://user-images.githubusercontent.com/7058205/188328658-163343e4-a6cf-48c5-b2b7-67723c5a114c.png)
![image](https://user-images.githubusercontent.com/7058205/188328572-3d971640-c8cc-41c0-a2c2-8a1dc4b9e684.png)

Thanks a lot for your help!

**Comment by VChet** [comment]
Should be fixed now

**Comment by timea-techgirl** [comment]
All perfect now, thank you so much!
